export const contributorData = [
    {
        id: "nakel-ola",
        url: "https://github.com/nakel-ola",
        avatar: "https://avatars.githubusercontent.com/u/109567025?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "nakel-ola",
    },
    {
        id: "ChrisM922",
        url: "https://github.com/ChrisM922",
        avatar: "https://avatars.githubusercontent.com/u/112943995?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "ChrisM922",
    },
    {
        id: "jaas666",
        url: "https://github.com/jaas666",
        avatar: "https://avatars.githubusercontent.com/u/30204147?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "jaas666",
    },
    {
        id: "radhey30",
        url: "https://github.com/radhey30",
        avatar: "https://avatars.githubusercontent.com/u/89542093?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "radhey30",
    },
    {
        id: "Akiva1992",
        url: "https://github.com/Akiva1992",
        avatar: "https://avatars.githubusercontent.com/u/107344160?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Akiva1992",
    },
    {
        id: "kabszac",
        url: "https://github.com/kabszac",
        avatar: "https://avatars.githubusercontent.com/u/69686216?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "kabszac",
    },
    {
        id: "HunterStarets",
        url: "https://github.com/HunterStarets",
        avatar: "https://avatars.githubusercontent.com/u/17518254?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "HunterStarets",
    },
    {
        id: "Rajdeep1311",
        url: "https://github.com/Rajdeep1311",
        avatar: "https://avatars.githubusercontent.com/u/113296626?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Rajdeep1311",
    },
    {
        id: "dependabot[bot]",
        url: "https://github.com/dependabot[bot]",
        avatar: "https://avatars.githubusercontent.com/u/49699333?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "dependabot[bot]",
    },
    {
        id: "DarshanDixit05",
        url: "https://github.com/DarshanDixit05",
        avatar: "https://avatars.githubusercontent.com/u/76871537?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "DarshanDixit05",
    },
    {
        id: "sakibian",
        url: "https://github.com/sakibian",
        avatar: "https://avatars.githubusercontent.com/u/40847839?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "sakibian",
    },
    {
        id: "Nkiriobasi",
        url: "https://github.com/Nkiriobasi",
        avatar: "https://avatars.githubusercontent.com/u/88588310?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Nkiriobasi",
    },
    {
        id: "Nitin-kumar199",
        url: "https://github.com/Nitin-kumar199",
        avatar: "https://avatars.githubusercontent.com/u/112743746?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Nitin-kumar199",
    },
    {
        id: "EmekaManuel",
        url: "https://github.com/EmekaManuel",
        avatar: "https://avatars.githubusercontent.com/u/107403276?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "EmekaManuel",
    },
    {
        id: "Ereakin",
        url: "https://github.com/Ereakin",
        avatar: "https://avatars.githubusercontent.com/u/98915665?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Ereakin",
    },
    {
        id: "Davidthecode",
        url: "https://github.com/Davidthecode",
        avatar: "https://avatars.githubusercontent.com/u/99010198?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Davidthecode",
    },
    {
        id: "Jonnie-Dev",
        url: "https://github.com/Jonnie-Dev",
        avatar: "https://avatars.githubusercontent.com/u/73708569?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Jonnie-Dev",
    },
    {
        id: "rangaraju29139",
        url: "https://github.com/rangaraju29139",
        avatar: "https://avatars.githubusercontent.com/u/30431968?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "rangaraju29139",
    },
    {
        id: "Himanshukrabc",
        url: "https://github.com/Himanshukrabc",
        avatar: "https://avatars.githubusercontent.com/u/68722052?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Himanshukrabc",
    },
    {
        id: "Chemin7",
        url: "https://github.com/Chemin7",
        avatar: "https://avatars.githubusercontent.com/u/67341387?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Chemin7",
    },
    {
        id: "srish-ti",
        url: "https://github.com/srish-ti",
        avatar: "https://avatars.githubusercontent.com/u/25656561?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "srish-ti",
    },
    {
        id: "Aishagojo",
        url: "https://github.com/Aishagojo",
        avatar: "https://avatars.githubusercontent.com/u/124359762?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Aishagojo",
    },
    {
        id: "alvarotorrestx",
        url: "https://github.com/alvarotorrestx",
        avatar: "https://avatars.githubusercontent.com/u/79110517?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "alvarotorrestx",
    },
    {
        id: "vinayyak",
        url: "https://github.com/vinayyak",
        avatar: "https://avatars.githubusercontent.com/u/60383210?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "vinayyak",
    },
    {
        id: "chiefkarim",
        url: "https://github.com/chiefkarim",
        avatar: "https://avatars.githubusercontent.com/u/73248301?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "chiefkarim",
    },
    {
        id: "python-fuse",
        url: "https://github.com/python-fuse",
        avatar: "https://avatars.githubusercontent.com/u/129158431?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "python-fuse",
    },
    {
        id: "KshitijTodkar48",
        url: "https://github.com/KshitijTodkar48",
        avatar: "https://avatars.githubusercontent.com/u/120639775?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "KshitijTodkar48",
    },
    {
        id: "pytechlady",
        url: "https://github.com/pytechlady",
        avatar: "https://avatars.githubusercontent.com/u/12651579?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "pytechlady",
    },
    {
        id: "Fulosophy",
        url: "https://github.com/Fulosophy",
        avatar: "https://avatars.githubusercontent.com/u/76975743?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Fulosophy",
    },
    {
        id: "Shahzaib-Iqbal-1057",
        url: "https://github.com/Shahzaib-Iqbal-1057",
        avatar: "https://avatars.githubusercontent.com/u/98122801?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Shahzaib-Iqbal-1057",
    },
    {
        id: "robgric3",
        url: "https://github.com/robgric3",
        avatar: "https://avatars.githubusercontent.com/u/49682982?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "robgric3",
    },
    {
        id: "dork7",
        url: "https://github.com/dork7",
        avatar: "https://avatars.githubusercontent.com/u/54894721?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "dork7",
    },
    {
        id: "avivk9",
        url: "https://github.com/avivk9",
        avatar: "https://avatars.githubusercontent.com/u/67284525?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "avivk9",
    },
    {
        id: "Broderick-Westrope",
        url: "https://github.com/Broderick-Westrope",
        avatar: "https://avatars.githubusercontent.com/u/55474351?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "Broderick-Westrope",
    },
    {
        id: "CodingLady22",
        url: "https://github.com/CodingLady22",
        avatar: "https://avatars.githubusercontent.com/u/99496129?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "CodingLady22",
    },
    {
        id: "SeaBebop",
        url: "https://github.com/SeaBebop",
        avatar: "https://avatars.githubusercontent.com/u/54507045?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "SeaBebop",
    },
    {
        id: "ht-l1",
        url: "https://github.com/ht-l1",
        avatar: "https://avatars.githubusercontent.com/u/106502799?v=4&h=300&w=300&fit=cover&mask=circle&maxage=7d",
        name: "ht-l1",
    },
];
